# In-class activity: Making your own college rankings

Cathy O'Neil's chapter, "Arms Race," from _Weapons of Math Destruction_ concludes with a proposed solution for the data manipulation that followed the rise of the U.S. News and World Report college rankings: an [open data portal from the U.S Department of Education](https://collegescorecard.ed.gov/).

You've had a chance to look at that portal -- now, you can explore some of the [data](https://collegescorecard.ed.gov/data) yourself, and build your own college ranking model.

#### Special Note: Organization of this notebook
This time, I've included a clean version up top, where you can work on the problems on your own, and the solutions down at the bottom, if you want to peek ahead to some potential ways to do each step.

I _highly encourage_ you to try it on your own first without peeking!

## Part 1: Load in the data and look at the data dictionary

As we saw, the full institution-level dataset from the US Department of Education has more than 6,000 different features in it! I've made a condensed version of it that only has ~115 different features/variables. This data file is available to download from Canvas called `"college_scorecard_2022.csv"`.

I've also provided a [condensed version of the *data dictionary*](https://docs.google.com/spreadsheets/d/1LjTVjLoXnD4OTKhT7Mw7lWuCvvKqhevZ4rywVfeLioQ/edit?usp=sharing) that explains what features/variables are and what kinds of values they contain.

### Step 1. Load the data file into this notebook and examine it.
* What do you notice?
* How many rows and how many columns does it have?
* Which columns are numeric and which are not?
* For the numeric values, what ranges do they have?

### Step 2. Peruse the simplified [data dictionary](https://docs.google.com/spreadsheets/d/1LjTVjLoXnD4OTKhT7Mw7lWuCvvKqhevZ4rywVfeLioQ/edit?usp=sharing) (which is in a Google Sheet).
* How is it organized?
* What information is relevant to you as you are making sense of this dataset?

In [1]:
# YOUR CODE HERE

# Import necessary packages
import pandas as pd
import numpy as np
# Read in data file
df= pd.read_csv('college_scorecard_2022.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6681 entries, 0 to 6680
Columns: 116 entries, Unnamed: 0 to ADMCON7
dtypes: float64(101), int64(6), object(9)
memory usage: 5.9+ MB

In [2]:
df

,Unnamed: 0,UNITID,INSTNM,CITY,STABBR,ZIP,INSTURL,HIGHDEG,CONTROL,ST_FIPS,...,PRGMOFR,BOOKSUPPLY,ROOMBOARD_ON,OTHEREXPENSE_ON,ROOMBOARD_OFF,OTHEREXPENSE_OFF,OTHEREXPENSE_FAM,ENDOWBEGIN,ENDOWEND,ADMCON7
0,0,100654,Alabama A & M University,Normal,AL,35762,www.aamu.edu/,4,1,1,...,NaN,1600.0,9240.0,3090.0,9240.0,3090.0,3440.0,NaN,NaN,1.0
1,1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,https://www.uab.edu/,4,1,1,...,NaN,1200.0,12307.0,5555.0,12307.0,5555.0,5555.0,537349307.0,539858544.0,1.0
2,2,100690,Amridge University,Montgomery,AL,36117-3553,www.amridgeuniversity.edu/,4,2,1,...,NaN,900.0,NaN,NaN,9600.0,1600.0,1600.0,174805.0,174818.0,NaN
3,3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,www.uah.edu/,4,1,1,...,NaN,2200.0,10652.0,4076.0,10652.0,4076.0,4076.0,77250279.0,75837207.0,1.0
4,4,100724,Alabama State University,Montgomery,AL,36104-0271,www.alasu.edu/,4,1,1,...,NaN,1600.0,6050.0,3392.0,7320.0,4228.0,4228.0,94536751.0,111315175.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6676,6676,49576719,Pennsylvania State University-Penn State Wilke...,Lehman,PA,18627-0217,wilkesbarre.psu.edu/,0,1,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6677,6677,49576720,Pennsylvania State University-Penn State York,York,PA,17403-3326,york.psu.edu/,0,1,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6678,6678,49576721,Pennsylvania State University-Penn State Great...,Malvern,PA,19355-1488,greatvalley.psu.edu/,0,1,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6679,6679,49576722,Pennsylvania State University-Penn State Harri...,Middletown,PA,17057-4846,harrisburg.psu.edu/,0,1,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6680,6680,49576723,Pennsylvania State University-Penn State Brand...,Media,PA,19063-5522,brandywine.psu.edu/,0,1,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(df.columns.tolist())

['Unnamed: 0', 'UNITID', 'INSTNM', 'CITY', 'STABBR', 'ZIP', 'INSTURL', 'HIGHDEG', 'CONTROL', 'ST_FIPS', 'REGION', 'LOCALE', 'CCBASIC', 'CCUGPROF', 'CCSIZSET', 'HBCU', 'PBI', 'ANNHI', 'TRIBAL', 'AANAPII', 'HSI', 'NANTI', 'MENONLY', 'WOMENONLY', 'RELAFFIL', 'ADM_RATE', 'SATVR25', 'SATVR75', 'SATMT25', 'SATMT75', 'SATVRMID', 'SATMTMID', 'ACTCMMID', 'ACTENMID', 'ACTMTMID', 'PCIP01', 'PCIP03', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP10', 'PCIP11', 'PCIP12', 'PCIP13', 'PCIP14', 'PCIP15', 'PCIP16', 'PCIP19', 'PCIP22', 'PCIP23', 'PCIP24', 'PCIP25', 'PCIP26', 'PCIP27', 'PCIP29', 'PCIP30', 'PCIP31', 'PCIP38', 'PCIP39', 'PCIP40', 'PCIP41', 'PCIP42', 'PCIP43', 'PCIP44', 'PCIP45', 'PCIP46', 'PCIP47', 'PCIP48', 'PCIP49', 'PCIP50', 'PCIP51', 'PCIP52', 'PCIP54', 'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF', 'NUM4_PRIV', 'COSTT4_A', 'INEXPFTE', 'AVGFACSAL', 'PFTFAC', 'PCTPELL', 'C150_4', 'PFTFTUG1_EF', 'D150_4', 'RET_FT4', 'PCTFLOAN', 'UG25ABV', 'GRAD_DEBT_MDN', 'FIRSTGEN_DEBT_MDN', 'NOTFIRSTGEN_DEBT_MDN', 'COUNT_NWNE_P10', 'COUNT_WNE_P10', 'MD_EARN_WNE_P10', 'PCT75_EARN_WNE_P10', 'COUNT_WNE_MALE0_P10', 'COUNT_WNE_MALE1_P10', 'UGDS_MEN', 'UGDS_WOMEN', 'PRGMOFR', 'BOOKSUPPLY', 'ROOMBOARD_ON', 'OTHEREXPENSE_ON', 'ROOMBOARD_OFF', 'OTHEREXPENSE_OFF', 'OTHEREXPENSE_FAM', 'ENDOWBEGIN', 'ENDOWEND', 'ADMCON7']

In [4]:
df.describe()

df["ADM_RATE"].max()

1.0

### Step 3. What are some basic ways you can filter and sort this data to look at some colleges you may be intersted in?

For example, Whitman is a small liberal arts college, which means it has a "Carnegie Classification--basic" (CCBASIC) value of 21. You might filter this data set to look at liberal arts colleges.

Or, Historically Black Colleges and Universities (HBCUs) are indicated in the HBCU column with either a 0 or a 1. You might filter this data set to look at HBCUs.

What are some other interesting ways you might filter this dataset?

As you are doing this, make sure to consult the data dictionary to see what the column names mean.

Pick a subset of colleges you want to focus on (i.e. HBCUs, liberal arts colleges, colleges in the Pacific Northwest, public universities, etc.) and make a new data frame with those colleges.

In [5]:
# Note: By default, Jupyter only shows 20 columns at a time
# You can override this by using the following line:
pd.options.display.max_columns = None

# You can also get a list of all of the columns with the following line:
print(df.columns.tolist())

['Unnamed: 0', 'UNITID', 'INSTNM', 'CITY', 'STABBR', 'ZIP', 'INSTURL', 'HIGHDEG', 'CONTROL', 'ST_FIPS', 'REGION', 'LOCALE', 'CCBASIC', 'CCUGPROF', 'CCSIZSET', 'HBCU', 'PBI', 'ANNHI', 'TRIBAL', 'AANAPII', 'HSI', 'NANTI', 'MENONLY', 'WOMENONLY', 'RELAFFIL', 'ADM_RATE', 'SATVR25', 'SATVR75', 'SATMT25', 'SATMT75', 'SATVRMID', 'SATMTMID', 'ACTCMMID', 'ACTENMID', 'ACTMTMID', 'PCIP01', 'PCIP03', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP10', 'PCIP11', 'PCIP12', 'PCIP13', 'PCIP14', 'PCIP15', 'PCIP16', 'PCIP19', 'PCIP22', 'PCIP23', 'PCIP24', 'PCIP25', 'PCIP26', 'PCIP27', 'PCIP29', 'PCIP30', 'PCIP31', 'PCIP38', 'PCIP39', 'PCIP40', 'PCIP41', 'PCIP42', 'PCIP43', 'PCIP44', 'PCIP45', 'PCIP46', 'PCIP47', 'PCIP48', 'PCIP49', 'PCIP50', 'PCIP51', 'PCIP52', 'PCIP54', 'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF', 'NUM4_PRIV', 'COSTT4_A', 'INEXPFTE', 'AVGFACSAL', 'PFTFAC', 'PCTPELL', 'C150_4', 'PFTFTUG1_EF', 'D150_4', 'RET_FT4', 'PCTFLOAN', 'UG25ABV', 'GRAD_DEBT_MDN', 'FIRSTGEN_DEBT_MDN', 'NOTFIRSTGEN_DEBT_MDN', 'COUNT_NWNE_P10', 'COUNT_WNE_P10', 'MD_EARN_WNE_P10', 'PCT75_EARN_WNE_P10', 'COUNT_WNE_MALE0_P10', 'COUNT_WNE_MALE1_P10', 'UGDS_MEN', 'UGDS_WOMEN', 'PRGMOFR', 'BOOKSUPPLY', 'ROOMBOARD_ON', 'OTHEREXPENSE_ON', 'ROOMBOARD_OFF', 'OTHEREXPENSE_OFF', 'OTHEREXPENSE_FAM', 'ENDOWBEGIN', 'ENDOWEND', 'ADMCON7']

In [6]:
# YOUR CODE HERE

# Select a subset of the colleges (however you like) and make a new dataframe
CS_df=df[df["ZIP"] == '99362'] 
CS_df

,Unnamed: 0,UNITID,INSTNM,CITY,STABBR,ZIP,INSTURL,HIGHDEG,CONTROL,ST_FIPS,REGION,LOCALE,CCBASIC,CCUGPROF,CCSIZSET,HBCU,PBI,ANNHI,TRIBAL,AANAPII,HSI,NANTI,MENONLY,WOMENONLY,RELAFFIL,ADM_RATE,SATVR25,SATVR75,SATMT25,SATMT75,SATVRMID,SATMTMID,ACTCMMID,ACTENMID,ACTMTMID,PCIP01,PCIP03,PCIP04,PCIP05,PCIP09,PCIP10,PCIP11,PCIP12,PCIP13,PCIP14,PCIP15,PCIP16,PCIP19,PCIP22,PCIP23,PCIP24,PCIP25,PCIP26,PCIP27,PCIP29,PCIP30,PCIP31,PCIP38,PCIP39,PCIP40,PCIP41,PCIP42,PCIP43,PCIP44,PCIP45,PCIP46,PCIP47,PCIP48,PCIP49,PCIP50,PCIP51,PCIP52,PCIP54,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,NUM4_PRIV,COSTT4_A,INEXPFTE,AVGFACSAL,PFTFAC,PCTPELL,C150_4,PFTFTUG1_EF,D150_4,RET_FT4,PCTFLOAN,UG25ABV,GRAD_DEBT_MDN,FIRSTGEN_DEBT_MDN,NOTFIRSTGEN_DEBT_MDN,COUNT_NWNE_P10,COUNT_WNE_P10,MD_EARN_WNE_P10,PCT75_EARN_WNE_P10,COUNT_WNE_MALE0_P10,COUNT_WNE_MALE1_P10,UGDS_MEN,UGDS_WOMEN,PRGMOFR,BOOKSUPPLY,ROOMBOARD_ON,OTHEREXPENSE_ON,ROOMBOARD_OFF,OTHEREXPENSE_OFF,OTHEREXPENSE_FAM,ENDOWBEGIN,ENDOWEND,ADMCON7
3505,3505,237057,Whitman College,Walla Walla,WA,99362,www.whitman.edu/,3,2,53,8,13.0,21.0,14.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.5413,620.0,710.0,610.0,720.0,665.0,665.0,31.0,33.0,29.0,0.0,0.0,0.0,0.0099,0.0074,0.0,0.0471,0.0,0.0,0.0149,0.0,0.0199,0.0,0.0,0.0645,0.0124,0.0,0.1762,0.0422,0.0,0.005,0.0,0.0496,0.0,0.0794,0.0,0.0844,0.0,0.0,0.2531,0.0,0.0,0.0,0.0,0.0968,0.0025,0.0,0.0347,0.6027,0.0254,0.0919,0.0717,0.0022,0.0045,0.0695,0.1031,0.0291,0.0381,235.0,69532.0,22105.0,9760.0,0.9015,0.1184,0.8575,0.8459,393.0,0.72,0.4072,0.0089,17300,13000,12000,34,255.0,59340.0,85781.0,151.0,103.0,0.4122,0.5878,NaN,1400.0,13800.0,800.0,13800.0,800.0,800.0,565255655.0,586334718.0,5.0

In [7]:
WA_df=df[df["STABBR"]=="WA"]
WA_df

,Unnamed: 0,UNITID,INSTNM,CITY,STABBR,ZIP,INSTURL,HIGHDEG,CONTROL,ST_FIPS,REGION,LOCALE,CCBASIC,CCUGPROF,CCSIZSET,HBCU,PBI,ANNHI,TRIBAL,AANAPII,HSI,NANTI,MENONLY,WOMENONLY,RELAFFIL,ADM_RATE,SATVR25,SATVR75,SATMT25,SATMT75,SATVRMID,SATMTMID,ACTCMMID,ACTENMID,ACTMTMID,PCIP01,PCIP03,PCIP04,PCIP05,PCIP09,PCIP10,PCIP11,PCIP12,PCIP13,PCIP14,PCIP15,PCIP16,PCIP19,PCIP22,PCIP23,PCIP24,PCIP25,PCIP26,PCIP27,PCIP29,PCIP30,PCIP31,PCIP38,PCIP39,PCIP40,PCIP41,PCIP42,PCIP43,PCIP44,PCIP45,PCIP46,PCIP47,PCIP48,PCIP49,PCIP50,PCIP51,PCIP52,PCIP54,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,NUM4_PRIV,COSTT4_A,INEXPFTE,AVGFACSAL,PFTFAC,PCTPELL,C150_4,PFTFTUG1_EF,D150_4,RET_FT4,PCTFLOAN,UG25ABV,GRAD_DEBT_MDN,FIRSTGEN_DEBT_MDN,NOTFIRSTGEN_DEBT_MDN,COUNT_NWNE_P10,COUNT_WNE_P10,MD_EARN_WNE_P10,PCT75_EARN_WNE_P10,COUNT_WNE_MALE0_P10,COUNT_WNE_MALE1_P10,UGDS_MEN,UGDS_WOMEN,PRGMOFR,BOOKSUPPLY,ROOMBOARD_ON,OTHEREXPENSE_ON,ROOMBOARD_OFF,OTHEREXPENSE_OFF,OTHEREXPENSE_FAM,ENDOWBEGIN,ENDOWEND,ADMCON7
61,61,102845,Charter College,Vancouver,WA,98683-7575,https://www.chartercollege.edu/,3,3,53,8,12.0,23.0,10.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0123,0.0000,0.0,0.0000,0.0000,0.0000,0.0360,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.000,0.000,0.0123,0.1089,0.0284,0.0077,0.0000,0.7040,0.0905,0.0000,0.3132,0.0415,0.1972,0.0189,0.0830,0.0486,0.1363,0.0005,0.1608,0.0000,486.0,31263.0,2269.0,4840.0,0.3361,0.5950,0.5169,0.9649,2095.0,NaN,0.6807,0.5901,14171,12666,12667,98,488.0,36609.0,55245.0,341.0,147.0,0.2217,0.7783,NaN,0.0,NaN,NaN,7223.0,8145.0,8145.0,NaN,NaN,NaN
3446,3446,234669,Bellevue College,Bellevue,WA,98007-6484,https://bellevuecollege.edu/,3,1,53,8,12.0,14.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0,0.0000,0.0000,0.0008,0.0958,0.0000,0.0334,0.0129,0.0012,0.0012,0.0000,0.0000,0.0000,0.5435,0.0,0.0028,0.0000,0.0,0.0008,0.0052,0.0000,0.0,0.0197,0.0028,0.0000,0.0016,0.000,0.000,0.0000,0.0000,0.0000,0.0000,0.0278,0.1196,0.1308,0.0000,0.3785,0.0513,0.1108,0.1699,0.0038,0.0038,0.1084,0.0890,0.0845,0.4610,NaN,15151.0,7647.0,9223.0,0.3403,0.0913,0.3426,0.4761,502.0,NaN,0.0465,0.2970,12500,8450,7975,381,1258.0,54232.0,82549.0,702.0,556.0,0.4443,0.5557,NaN,930.0,13530.0,3714.0,11118.0,3714.0,3216.0,10088779.0,11608886.0,NaN
3447,3447,234696,Bellingham Technical College,Bellingham,WA,98225-1599,https://www.btc.edu/,3,1,53,8,13.0,14.0,7.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0517,0.0103,0.0,0.0000,0.0000,0.0000,0.1211,0.0162,0.0000,0.0000,0.1477,0.0000,0.0133,0.0015,0.0000,0.0118,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0,0.0000,0.0044,0.0000,0.0000,0.000,0.000,0.0561,0.1344,0.0547,0.0000,0.0000,0.2245,0.1521,0.0000,0.6256,0.0095,0.1232,0.0427,0.0095,0.0000,0.1185,0.0000,0.0711,0.3460,NaN,11694.0,8825.0,8319.0,1.0000,0.3849,0.5238,0.2143,42.0,NaN,0.1720,0.5049,18732,9500,9557,114,463.0,45357.0,73508.0,205.0,258.0,0.4408,0.5592,NaN,930.0,NaN,NaN,10500.0,3474.0,3228.0,3224436.0,3325707.0,NaN
3448,3448,234711,Big Bend Community College,Moses Lake,WA,98837-3299,https://www.bigbend.edu/,2,1,53,8,33.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0091,0.0000,0.0,0.0000,0.0000,0.0000,0.0443,0.0000,0.1745,0.0039,0.0065,0.0000,0.0000,0.0000,0.0000,0.4258,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0,0.0039,0.0000,0.0000,0.0039,0.000,0.000,0.0247,0.0352,0.0169,0.0768,0.0000,0.1003,0.0742,0.0000,0.4757,0.0072,0.4092,0.0151,0.0033,0.0013,0.0533,0.0000,0.0349,0.2553,NaN,14610.0,7601.0,8139.0,1.0000,0.3144,NaN,0.6390,NaN,NaN,0.0821,0.2830,10505,7277,8028,218,742.0,38489.0,57429.0,418.0,324.0,0.4191,0.5809,NaN,930.0,8364.0,3690.0,10500.0,3876.0,3630.0,2024942.0,2167544.0,NaN
3449,3449,234827,Central Washington University,Ellensburg,WA,98926,www.cwu.edu/,4,1,53,8,32.0,18.0,11.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.8599,470.0,580.0,460.0,570.0,525.0,515.0,21.0,19.0,20.0,0.0000,0.0019,0.0,0.0004,0.0253,0.0000,0.0586,0.0027,0.0945,0.0000,0.0371,0.0100,0.0245,0.0000,0.0218,0.0019,0.0,0.0463,0.0034,0.0,0.0046,0.0253,0.0046,0.0,0.0172,0.0000,0.0712,0.0528,0.021,0.098,0.0000,0.0000,0.0000,0.0165,0.0601,0.0421,0.2488,0.0096,0.5156,0.0441,0.1781,0.0493,0.0064,0.0097,0.0895,0.0264,0.0808,0.1223,NaN,24008.0,10194.0,7710.0,0.6178,0.3384,0.5835,0.5474,1198.0,0.7041,0.4765,0.1907,20194,13168,13000,416,3469.0,55685.0,75914.0,1810.0,1657.0,0.4648,0.5352,NaN,900.0,13787.0,2922.0,9276.0,2922.0,2922.0,38999287.0,40743517.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6314,6314,17706515,Columbia College - Naval Station Everett/Marys...,Marysville,WA,98271-7854,www.ccis.edu/locations/marysville.aspx,0,2,53,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24000,14275,14183,NaN,4136.0,43125.0,64957.0,2771.0,1365.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6325,6325,17706527,Columbia College - Whidbey Island,Oak Harbor,WA,98278-1000,www.ccis.edu/locations/whidbey-island.aspx,0,2,53,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24000,14275,14183,NaN,4136.0,43125.0,64957.0,2771.0,1365.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6426,6426,23693901,Washington State University-Vancouver,Vancouver,WA,98686-9600,https://www.vancouver.wsu.edu/,0,1,53,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20000,14500,14250,694,6274.0,61080.0,87360.0,3259.0,3015.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6427,6427,23693902,Washington State University-Spokane,Spokane,WA,99202-9600,https://spokane.wsu.edu/,0,1,53,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20000,14500,14250,694,6274.0,61080.0,87360.0,3259.0,3015.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6428,6428,23693903,Washington State University-Tri Cities,Richland,WA,99354-1671,https://tricities.wsu.edu/,0,1,53,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20000,14500,14250,694,6274.0,61080.0,87360.0,3259.0,3015.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Part 2: Making your own college ranking

What features/columns are important to _you_ in selecting a college? (Or, since you have already gone through this process, you might think about a sibling or a friend who is thinking about what college they might want to attend.)

### Step 4. Pick a subset of the columns (at least 5, but no more than 10) that you want to include in your custom ranking

Using the data dictionary, highlight the features / columns that you want to include in your custom ranking. (Remember that column D in the data dictionary, VARIABLE NAME, is the one that has the column name in your data frame.)

Make a new data frame that just has the institution name and these 5-10 columns that you are interested in.

In [8]:
# YOUR CODE HERE

# Select a subset of columns and make a new data frame
name= df[df["INSTNM"]=='Whitman College']
name
# Hint: Remember that you can select many columns at once using a list
df.columns.tolist()

['Unnamed: 0',
 'UNITID',
 'INSTNM',
 'CITY',
 'STABBR',
 'ZIP',
 'INSTURL',
 'HIGHDEG',
 'CONTROL',
 'ST_FIPS',
 'REGION',
 'LOCALE',
 'CCBASIC',
 'CCUGPROF',
 'CCSIZSET',
 'HBCU',
 'PBI',
 'ANNHI',
 'TRIBAL',
 'AANAPII',
 'HSI',
 'NANTI',
 'MENONLY',
 'WOMENONLY',
 'RELAFFIL',
 'ADM_RATE',
 'SATVR25',
 'SATVR75',
 'SATMT25',
 'SATMT75',
 'SATVRMID',
 'SATMTMID',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP12',
 'PCIP13',
 'PCIP14',
 'PCIP15',
 'PCIP16',
 'PCIP19',
 'PCIP22',
 'PCIP23',
 'PCIP24',
 'PCIP25',
 'PCIP26',
 'PCIP27',
 'PCIP29',
 'PCIP30',
 'PCIP31',
 'PCIP38',
 'PCIP39',
 'PCIP40',
 'PCIP41',
 'PCIP42',
 'PCIP43',
 'PCIP44',
 'PCIP45',
 'PCIP46',
 'PCIP47',
 'PCIP48',
 'PCIP49',
 'PCIP50',
 'PCIP51',
 'PCIP52',
 'PCIP54',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 'PPTUG_EF',
 'NUM4_PRIV',
 'COSTT4_A',
 'INEXPFTE',
 'AVGFACSAL',
 'PFTFAC',
 'PCTPELL',
 'C150_4',
 'PFTFTUG1_EF',
 'D150_4',
 'RET_FT4',
 'PCTFLOAN',
 'UG25ABV',
 'GRAD_DEBT_MDN',
 'FIRSTGEN_DEBT_MDN',
 'NOTFIRSTGEN_DEBT_MDN',
 'COUNT_NWNE_P10',
 'COUNT_WNE_P10',
 'MD_EARN_WNE_P10',
 'PCT75_EARN_WNE_P10',
 'COUNT_WNE_MALE0_P10',
 'COUNT_WNE_MALE1_P10',
 'UGDS_MEN',
 'UGDS_WOMEN',
 'PRGMOFR',
 'BOOKSUPPLY',
 'ROOMBOARD_ON',
 'OTHEREXPENSE_ON',
 'ROOMBOARD_OFF',
 'OTHEREXPENSE_OFF',
 'OTHEREXPENSE_FAM',
 'ENDOWBEGIN',
 'ENDOWEND',
 'ADMCON7']

### Step 5: Normalizing the data values

Look at the columns that you have picked. Is there a way to add them all together to come up with a single score?

To do this, we have to think about:
* What types of data do they contain?
* Are some numeric? For the numeric values, what range do they have (max and min)?
* Are some categorial or quantitative?

Figure out a way to turn each column into a number on a shared scale (i.e. 0 to 1, or -1 to 1). This process is called **normalization**.

As you do this, think about what values you are imbuing into the data. Are you assuming that some values are preferable to others?

For example, how might we normalize the values for "Instructional expenditures per full-time equivalent student" (INEXPFTE) for liberal arts colleges?

First, we would look at the range of values in the dataframe.

In [9]:
# A generalized way to do this is what is called min-max normalization:

# SCALED VALUE = (OLD VALUE - MIN) / (MAX - MIN)

# Or, to put it in terms of dataframes:

# df[scaled_column] = (df[column] - df[column].min()) / (df[column].max() - df[column].min())

# You can also write a for loop to iterate over all the columns in your data frame to do this!
# But, depending on the columns you chose, this might not work for all of them.

# More on min-max normalization here: https://towardsdatascience.com/everything-you-need-to-know-about-min-max-normalization-in-python-b79592732b79

## Part 4: Adding the columns together & weighting them

Now that you have normalized your columns, you can add them all together.

### Step 6: Create a new column that sums the other columns. 

This new column is your rank.

Which colleges have the highest overall scores?

In [10]:
# YOUR CODE HERE

# Create a new column that adds the normalized values

In [11]:
# What is the result?

# Display the ranking by using .sort_values()

# You can also use .rank() to add in a ranking
# See: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rank.html

### Step 7: Create *weights* for each column

Right now, each column as an equal weight. That is, all of the 10 (or 20) features you picked contribute the same amount to the overall score. But that might not be what you want.

Think about how you might weigh each column on a value between 0 and 1. If something has a weight of 1, it is really important. If it has a weight of 0, it is not important at all (and in fact won't be included in the model). Or, if you have 5 columns, you might rank them and give each one a weight between 1 and 5.

Are there any columns that should have a negative weight (i.e., it should detract from the overall score)?

_For folks taking machine learning, this is how many ML algorithms work!_ The difference is that you use a mathematical model to determine the weights, instead of a human's preferences.

Come up with weights for each of the columns you picked. Now, calculate a new total using these weights.

How has the ranking changed?

In [12]:
# YOUR CODE HERE

# You can do this by writing out a formula

# You might also make a dictionary of weights and use that to calculate the weighted values

In [13]:
# What are the new rankings?

_______
### Professor Wirfs-Brock's sample solution

Only peek at this if you need to!

In [14]:
# YOUR CODE HERE
# Import necessary packages
import pandas as pd
import numpy as np

# Load in the .csv as a data frame
df = pd.read_csv("college_scorecard_2022.csv")

# Examine your data frame

In [15]:
# For example, say we are focusing on a ranking for liberal arts colleges
# We might make a liberal arts data frame

liberal_arts = df[df["CCBASIC"] == 21]

In [16]:
# If we want to focus on HBCUs:

HBCUs = df[df["HBCU"] == 1]

In [17]:
# Picking a subset of columns:

# For example, let's focus on liberal arts colleges using the following criteria:

# Admission rate - ADM_RATE
# Percentage of degrees awarded in Computer And Information Sciences And Support Services. - PCIP11
# Percentage of degrees awarded in English Language And Literature/Letters. - PCIP23
# Average cost of attendance (academic year institutions) - COSTT4_A
# Median earnings of students working and not enrolled 10 years after entry - MD_EARN_WNE_P10
# Instructional expenditures per full-time equivalent student - INEXPFTE

liberal_arts_ranking = liberal_arts[["INSTNM","ADM_RATE","PCIP11","PCIP23","COSTT4_A","MD_EARN_WNE_P10","INEXPFTE" ]]

In [18]:
# Normalizing the values

# We might first use .describe() to look at the range of values:
liberal_arts_ranking["INEXPFTE"].describe()

count      233.000000
mean     15641.072961
std       8354.306625
min       1709.000000
25%       9848.000000
50%      13608.000000
75%      19896.000000
max      48373.000000
Name: INEXPFTE, dtype: float64

In [19]:
# We can scale the max, 48373 to 1, and the min, 1709, to 0.

# The first way we might do this is just by calculating a new column using the min-max-scaling-method:
# SCALED VALUE = (OLD VALUE - MIN) / (MAX - MIN)

liberal_arts_ranking["INEXPFTE_s"] = (liberal_arts_ranking["INEXPFTE"] - 1709)/(48373-1709)

/var/folders/9s/_42jg5ds12l364yqldkmcvvw0000gn/T/ipykernel_26914/1326181397.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liberal_arts_ranking["INEXPFTE_s"] = (liberal_arts_ranking["INEXPFTE"] - 1709)/(48373-1709)

In [20]:
# Let's look at the new distribution,
# notice how the max is 1 and the min is 0
liberal_arts_ranking["INEXPFTE_s"].describe()

count    233.000000
mean       0.298561
std        0.179031
min        0.000000
25%        0.174417
50%        0.254993
75%        0.389744
max        1.000000
Name: INEXPFTE_s, dtype: float64

In [21]:
# And here's how we might normalize ALL the columns at once:

# here's where we make a new dataframe with just the columns are are interested in
liberal_arts_ranking = liberal_arts[["INSTNM","ADM_RATE","PCIP11","PCIP23","COSTT4_A","MD_EARN_WNE_P10","INEXPFTE" ]]

# make a copy the data frame
liberal_arts_normalized = liberal_arts_ranking.copy()

# list of columns we want to normalize
to_normalize = ["ADM_RATE","PCIP11","PCIP23","COSTT4_A","MD_EARN_WNE_P10","INEXPFTE"]

# apply normalization techniques
for column in to_normalize:
    liberal_arts_normalized[column] = (liberal_arts_normalized[column] - liberal_arts_normalized[column].min()) / (liberal_arts_normalized[column].max() - liberal_arts_normalized[column].min())

# view normalized data
# Note how all the maxes are 1 and all the mins are 0
liberal_arts_normalized.describe()

,ADM_RATE,PCIP11,PCIP23,COSTT4_A,MD_EARN_WNE_P10,INEXPFTE
count,220.000000,234.000000,234.000000,225.000000,218.000000,233.000000
mean,0.585830,0.134946,0.224622,0.600037,0.333898,0.298561
std,0.256855,0.141752,0.163515,0.267034,0.153266,0.179031
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.446494,0.000000,0.113506,0.387173,0.226274,0.174417
50%,0.650260,0.113053,0.206897,0.646658,0.321027,0.254993
75%,0.771264,0.219912,0.315961,0.813810,0.426130,0.389744
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [28]:
# Calculating the total score:

# we can use the list of columns we care about, to_normalize, to do a sum
liberal_arts_normalized["score"] = liberal_arts_normalized[to_normalize].sum(axis=1)

liberal_arts_normalized.sort_values("score", ascending=False).head(50)

,INSTNM,ADM_RATE,PCIP11,PCIP23,COSTT4_A,MD_EARN_WNE_P10,INEXPFTE,score,rank,weighted_score
304,Harvey Mudd College,0.103307,1.000000,0.000000,1.000000,1.000000,0.622128,3.725436,1.0,12.455921
1512,Williams College,0.071895,0.457965,0.318704,0.939944,0.557172,1.000000,3.345680,2.0,12.647156
2052,Bard College,0.534565,0.000000,0.680251,0.924164,0.223487,0.730113,3.092580,3.0,13.149575
1017,DePauw University,0.662206,0.359735,0.309822,0.811823,0.448822,0.429946,3.022354,4.0,12.425252
2536,Kenyon College,0.312687,0.000000,0.886625,0.925449,0.443326,0.449811,3.017898,5.0,11.210575
1402,Amherst College,0.035505,0.439381,0.357367,0.958324,0.556686,0.654787,3.002050,6.0,10.433090
1628,Carleton College,0.138923,0.480531,0.264368,0.921340,0.504146,0.676603,2.985911,7.0,10.821949
3444,Washington and Lee University,0.175755,0.138938,0.222571,0.915736,0.727906,0.797231,2.978137,8.0,12.256584
1507,Wellesley College,0.130406,0.507965,0.239812,0.935132,0.497026,0.663166,2.973508,9.0,10.672932
3484,University of Puget Sound,0.865280,0.242478,0.190700,0.828649,0.441478,0.389744,2.958328,10.0,13.271159
2758,Bryn Mawr College,0.328946,0.234956,0.481714,0.910357,0.488059,0.511529,2.955560,11.0,11.253485
923,Knox College,0.688198,0.278319,0.694357,0.713901,0.289461,0.265622,2.929859,12.0,11.377704
3384,Hollins University,0.798252,0.000000,1.000000,0.646658,0.134969,0.309553,2.889433,13.0,11.924937
1475,Mount Holyoke College,0.485013,0.313717,0.379833,0.851153,0.333602,0.500321,2.863639,14.0,11.358266
441,Scripps College,0.293220,0.210619,0.362069,0.970846,0.477835,0.543760,2.858349,15.0,11.073732
1452,College of the Holy Cross,0.324300,0.081416,0.420585,0.879096,0.711712,0.429967,2.847077,16.0,11.256629
2137,Hobart William Smith Colleges,0.588652,0.144690,0.421108,0.922834,0.454959,0.314439,2.846682,17.0,11.582443
587,Trinity College,0.303285,0.172124,0.325496,0.959818,0.518185,0.550446,2.829354,18.0,11.200980
1561,Kalamazoo College,0.726800,0.292035,0.344828,0.764932,0.363811,0.336319,2.828725,19.0,11.837245
1397,Washington College,0.792611,0.124779,0.311390,0.788796,0.477065,0.333640,2.828281,20.0,12.572328
486,Westmont College,0.680677,0.249558,0.327586,0.771387,0.420331,0.372536,2.822075,21.0,11.900168
2081,Colgate University,0.208495,0.260619,0.278997,0.932174,0.612366,0.523658,2.816309,22.0,10.666010
2935,Washington & Jefferson College,0.902113,0.143363,0.246604,0.750078,0.469400,0.301560,2.813118,23.0,12.888555
251,Claremont McKenna College,0.052207,0.344690,0.065308,0.954215,0.734433,0.656523,2.807377,24.0,10.580270
2809,Haverford College,0.106294,0.368584,0.306165,0.952855,0.528550,0.544060,2.806508,25.0,9.962093
2918,Swarthmore College,0.004867,0.420796,0.097179,0.916215,0.569362,0.773830,2.782249,26.0,10.318293
1511,Wheaton College (Massachusetts),0.757328,0.139823,0.294671,0.864228,0.404658,0.313389,2.774097,27.0,12.122111
2053,Barnard College,0.055082,0.207080,0.389760,0.973387,0.558001,0.586405,2.769714,28.0,10.042770
3343,Bennington College,0.568189,0.102212,0.513584,0.946698,0.232431,0.406395,2.769510,29.0,11.314895
1091,Grinnell College,0.117575,0.458407,0.311390,0.862629,0.413590,0.599134,2.762726,30.0,9.741270
2759,Bucknell University,0.319766,0.083186,0.208986,0.938151,0.753187,0.452940,2.756216,31.0,11.284358
2296,Vassar College,0.176087,0.239381,0.274295,0.935207,0.447282,0.677160,2.749412,32.0,10.678289
3505,Whitman College,0.503374,0.208407,0.336991,0.850465,0.411837,0.437082,2.748156,33.0,11.227241
1498,Smith College,0.308594,0.243363,0.295193,0.934699,0.377233,0.584862,2.743945,34.0,10.816110
2802,Gettysburg College,0.438226,0.128761,0.438349,0.885103,0.489859,0.359035,2.739333,35.0,10.841996
400,Pomona College,0.000000,0.371681,0.115987,0.923776,0.528041,0.785531,2.725016,36.0,10.200331
2929,Ursinus College,0.794381,0.070354,0.231975,0.851541,0.493781,0.277902,2.719934,37.0,12.292128
2736,Willamette University,0.791395,0.123894,0.305120,0.803903,0.384542,0.306725,2.715579,38.0,12.064125
2827,Lafayette College,0.298086,0.162389,0.100313,0.917470,0.715100,0.506729,2.700088,39.0,11.102804
590,Wesleyan University,0.135826,0.154425,0.384535,0.942529,0.515638,0.564161,2.697113,40.0,10.149378
2132,Hamilton College,0.108284,0.134513,0.370951,0.890184,0.589537,0.601534,2.695004,41.0,10.272313
2701,Lewis & Clark College,0.787524,0.102212,0.302508,0.838556,0.325072,0.327426,2.683298,42.0,12.000404
3570,Lawrence University,0.666962,0.229204,0.371996,0.740395,0.287542,0.372171,2.668270,43.0,11.246309
2726,Reed College,0.372968,0.257965,0.253396,0.940930,0.310477,0.525673,2.661409,44.0,10.594267
3120,The University of the South,0.524831,0.094248,0.531348,0.747583,0.377055,0.371271,2.646337,45.0,10.809361
767,Covenant College,0.983630,0.140708,0.545977,0.549932,0.255971,0.168010,2.644227,46.0,11.799809
2917,Susquehanna University,0.712532,0.142035,0.413793,0.779158,0.393463,0.197090,2.638071,47.0,11.051208
2745,Allegheny College,0.713748,0.223009,0.263323,0.781264,0.392646,0.259172,2.633162,48.0,11.215301
1070,Wabash College,0.603805,0.000000,0.531348,0.689649,0.460231,0.341077,2.626109,49.0,11.245660
2779,Dickinson College,0.475943,0.152655,0.170324,0.912001,0.532934,0.376629,2.620485,50.0,10.952412

In [23]:
# And we can make a new column with the rank as well using the .rank method
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rank.html

liberal_arts_normalized["rank"] = liberal_arts_normalized["score"].rank(ascending=False)

liberal_arts_normalized

,INSTNM,ADM_RATE,PCIP11,PCIP23,COSTT4_A,MD_EARN_WNE_P10,INEXPFTE,score,rank
10,Birmingham-Southern College,0.573277,0.091593,0.108150,0.297306,0.310371,0.209412,1.590109,191.0
29,Judson College,0.529366,0.000000,0.156217,0.295303,0.059150,0.282509,1.322546,203.0
47,Spring Hill College,0.503705,0.000000,0.146290,0.645926,0.277022,0.134365,1.707309,182.0
48,Stillman College,0.518859,0.000000,0.108673,0.224847,0.089679,0.030430,0.972488,213.0
49,Talladega College,NaN,0.219912,0.064786,0.173369,0.045444,0.047017,0.550527,228.0
...,...,...,...,...,...,...,...,...,...
5009,Pacific Rim Christian University,0.568300,0.000000,0.000000,0.157096,NaN,0.011208,0.736603,225.0
5495,Antioch College,0.840062,0.000000,0.326541,0.564322,NaN,0.399773,2.130698,129.0
5520,Ana G. Mendez University,NaN,0.000000,0.000000,0.104735,NaN,0.049460,0.154195,234.0
5692,University of Arizona-Sierra Vista,NaN,0.152655,0.060084,NaN,0.362851,0.226384,0.801974,221.0
5741,Huntington University of Health Sciences,NaN,0.000000,0.000000,0.216270,NaN,0.000000,0.216270,233.0

In [24]:
# And where is Whitman?
liberal_arts_normalized[liberal_arts_normalized["INSTNM"] == "Whitman College"]

,INSTNM,ADM_RATE,PCIP11,PCIP23,COSTT4_A,MD_EARN_WNE_P10,INEXPFTE,score,rank
3505,Whitman College,0.503374,0.208407,0.336991,0.850465,0.411837,0.437082,2.748156,33.0

In [25]:
# Adding in weights

# How might we do the weighting? You could write out a long formula -- that is fine!
# But we can also expedite it with a dictionary.
# Here, our keys are the column names, and our values are the weights.
# For example:

weights = {"ADM_RATE":7,"PCIP11":1,"PCIP23":2,"COSTT4_A":3,"MD_EARN_WNE_P10":4,"INEXPFTE":6}

# Now we can make a new column using the weights
liberal_arts_normalized['weighted_score'] = sum([liberal_arts_normalized[key] * weights[key] for key in weights.keys()])

# view weighted data
liberal_arts_normalized.sort_values("weighted_score", ascending=False).head(50)

,INSTNM,ADM_RATE,PCIP11,PCIP23,COSTT4_A,MD_EARN_WNE_P10,INEXPFTE,score,rank,weighted_score
3484,University of Puget Sound,0.865280,0.242478,0.190700,0.828649,0.441478,0.389744,2.958328,10.0,13.271159
2052,Bard College,0.534565,0.000000,0.680251,0.924164,0.223487,0.730113,3.092580,3.0,13.149575
2935,Washington & Jefferson College,0.902113,0.143363,0.246604,0.750078,0.469400,0.301560,2.813118,23.0,12.888555
1512,Williams College,0.071895,0.457965,0.318704,0.939944,0.557172,1.000000,3.345680,2.0,12.647156
1397,Washington College,0.792611,0.124779,0.311390,0.788796,0.477065,0.333640,2.828281,20.0,12.572328
304,Harvey Mudd College,0.103307,1.000000,0.000000,1.000000,1.000000,0.622128,3.725436,1.0,12.455921
1017,DePauw University,0.662206,0.359735,0.309822,0.811823,0.448822,0.429946,3.022354,4.0,12.425252
2929,Ursinus College,0.794381,0.070354,0.231975,0.851541,0.493781,0.277902,2.719934,37.0,12.292128
3444,Washington and Lee University,0.175755,0.138938,0.222571,0.915736,0.727906,0.797231,2.978137,8.0,12.256584
1511,Wheaton College (Massachusetts),0.757328,0.139823,0.294671,0.864228,0.404658,0.313389,2.774097,27.0,12.122111
2736,Willamette University,0.791395,0.123894,0.305120,0.803903,0.384542,0.306725,2.715579,38.0,12.064125
2631,Wittenberg University,0.982303,0.059292,0.322362,0.606700,0.341823,0.208791,2.521271,72.0,12.020273
2701,Lewis & Clark College,0.787524,0.102212,0.302508,0.838556,0.325072,0.327426,2.683298,42.0,12.000404
3384,Hollins University,0.798252,0.000000,1.000000,0.646658,0.134969,0.309553,2.889433,13.0,11.924937
486,Westmont College,0.680677,0.249558,0.327586,0.771387,0.420331,0.372536,2.822075,21.0,11.900168
3412,Randolph College,0.896361,0.000000,0.208986,0.691293,0.265270,0.341291,2.403201,89.0,11.875205
1561,Kalamazoo College,0.726800,0.292035,0.344828,0.764932,0.363811,0.336319,2.828725,19.0,11.837245
2133,Hartwick College,0.934410,0.037168,0.175549,0.715187,0.303369,0.256515,2.422197,85.0,11.827259
767,Covenant College,0.983630,0.140708,0.545977,0.549932,0.255971,0.168010,2.644227,46.0,11.799809
1005,Wheaton College,0.866386,0.110619,0.364681,0.572391,0.342333,0.301174,2.557586,63.0,11.798239
1675,Saint Johns University,0.804778,0.226106,0.070010,0.707610,0.522911,0.262322,2.593739,56.0,11.787985
2702,Linfield University-McMinnville Campus,0.791505,0.065044,0.229885,0.685390,0.501374,0.257415,2.530614,70.0,11.671508
3353,Saint Michael's College,0.875899,0.123009,0.357367,0.736301,0.353327,0.174417,2.620319,51.0,11.637745
2137,Hobart William Smith Colleges,0.588652,0.144690,0.421108,0.922834,0.454959,0.314439,2.846682,17.0,11.582443
2786,Elizabethtown College,0.852892,0.256195,0.140543,0.483555,0.399386,0.322518,2.455090,81.0,11.490850
2989,Furman University,0.626369,0.131858,0.179206,0.817098,0.400026,0.414088,2.568645,61.0,11.410777
923,Knox College,0.688198,0.278319,0.694357,0.713901,0.289461,0.265622,2.929859,12.0,11.377704
1475,Mount Holyoke College,0.485013,0.313717,0.379833,0.851153,0.333602,0.500321,2.863639,14.0,11.358266
1672,College of Saint Benedict,0.833868,0.041150,0.207419,0.719804,0.376617,0.230392,2.409250,87.0,11.341295
3343,Bennington College,0.568189,0.102212,0.513584,0.946698,0.232431,0.406395,2.769510,29.0,11.314895
2857,Moravian University,0.790621,0.088938,0.136886,0.701349,0.434630,0.260843,2.413268,86.0,11.304683
2759,Bucknell University,0.319766,0.083186,0.208986,0.938151,0.753187,0.452940,2.756216,31.0,11.284358
1452,College of the Holy Cross,0.324300,0.081416,0.420585,0.879096,0.711712,0.429967,2.847077,16.0,11.256629
2758,Bryn Mawr College,0.328946,0.234956,0.481714,0.910357,0.488059,0.511529,2.955560,11.0,11.253485
2166,Marymount Manhattan College,0.879991,0.000000,0.187565,0.695581,0.281299,0.250729,2.295165,103.0,11.251380
3570,Lawrence University,0.666962,0.229204,0.371996,0.740395,0.287542,0.372171,2.668270,43.0,11.246309
1070,Wabash College,0.603805,0.000000,0.531348,0.689649,0.460231,0.341077,2.626109,49.0,11.245660
3505,Whitman College,0.503374,0.208407,0.336991,0.850465,0.411837,0.437082,2.748156,33.0,11.227241
2745,Allegheny College,0.713748,0.223009,0.263323,0.781264,0.392646,0.259172,2.633162,48.0,11.215301
1213,Centre College,0.701914,0.124779,0.191745,0.657895,0.395678,0.372364,2.444375,82.0,11.212247
2536,Kenyon College,0.312687,0.000000,0.886625,0.925449,0.443326,0.449811,3.017898,5.0,11.210575
1079,Cornell College,0.816171,0.132301,0.312435,0.681146,0.295775,0.251050,2.488878,77.0,11.203207
587,Trinity College,0.303285,0.172124,0.325496,0.959818,0.518185,0.550446,2.829354,18.0,11.200980
3428,Sweet Briar College,0.744719,0.093363,0.385057,0.391760,0.282531,0.467534,2.364964,96.0,11.187115
1062,Saint Mary's College,0.806216,0.000000,0.138454,0.692428,0.380029,0.276959,2.294086,104.0,11.179573
1364,Goucher College,0.782989,0.115929,0.359979,0.752544,0.277816,0.237656,2.526913,71.0,11.111642
2827,Lafayette College,0.298086,0.162389,0.100313,0.917470,0.715100,0.506729,2.700088,39.0,11.102804
2859,Muhlenberg College,0.592412,0.108407,0.177638,0.848687,0.521881,0.308032,2.557058,64.0,11.092347
1259,Transylvania University,0.923570,0.222566,0.087774,0.604877,0.301118,0.199640,2.339547,101.0,11.080053
441,Scripps College,0.293220,0.210619,0.362069,0.970846,0.477835,0.543760,2.858349,15.0,11.073732

In [26]:
# Now where is Whitman?